apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: result
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: result
  minReplicas: {{ .Values.result.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.result.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.result.autoscaling.targetCPU }}